# Generated by Django 2.1 on 2019-12-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=200)),
                ('rotation_period', models.CharField(max_length=100)),
                ('orbital_period', models.CharField(max_length=100)),
                ('gravity', models.CharField(max_length=100)),
                ('films', models.CharField(max_length=1000)),
                ('images', models.ImageField(blank=True, default='images/yoda.png', upload_to='')),
            ],
        ),
    ]
