# Generated by Django 2.1 on 2019-12-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='images',
            field=models.ImageField(blank=True, default='https://image.cnbcfm.com/api/v1/image/106256503-1574274174070yoda.jpg?v=1574274186&w=740&h=416', upload_to=''),
        ),
        migrations.AlterField(
            model_name='planet',
            name='planet_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
